### PR TITLE
Stackification

### PR DESCRIPTION
**Pull request by bitemyapp**

### CODE REVIEW

**Comment by jwiegley** [comment]
@bitemyapp Thanks for the pull request, Chris, but I don't include Stack or Nix files in my source projects since they can be generated from the Cabal file.

**Comment by bitemyapp** [comment]
:stuck_out_tongue: fair enough

**Comment by jwiegley** [comment]
@bitemyapp On a barely related note, you can see my attempt to formalize the connection between a simple initial and final encoding here: https://github.com/jwiegley/coq-haskell/blob/master/src/Control/Iso.v#L1161.  I'm stuck on one proof; plus, there are parametricity axioms to be verified.  But the hope would be to generalize this to be able to show that any ADT's final encoding is always isomorphic.

**Comment by bitemyapp** [comment]
@jwiegley I'm the only person that has that repo forked, lol. Pulled what you've added since then, thank you :)

**Pull request closed without merging**
